add_subdirectory(common)
add_subdirectory(q4_0-q8_0-IME-upstream)
add_subdirectory(q4_0-q8_0-IME-m4b)
add_subdirectory(q4_0-q8_0-IME-m4i)
add_subdirectory(q4_0-q8_0-IME-m4i-CB)
add_subdirectory(q4_0-q8_0-IME-m8b)
add_subdirectory(q4_0-q8_0-IME-m8b-CB)
add_subdirectory(q4_0-q8_0-IME-m8b-DPU)
add_subdirectory(q4_0-q8_0-IME-m8b-DPU-CB)
add_subdirectory(q4_0-q8_0-IME-m4n32b)
add_subdirectory(q4_0-q8_0-IME-m32n4)
add_subdirectory(q4_0-q8_0-RVV-group)
add_subdirectory(q4_0-q8_0-RVV-my)
add_subdirectory(q4_0-q8_0-RVV-upstream)
add_subdirectory(q4_K-q8_K-RVV-group)
add_subdirectory(q4_K-q8_K-RVV-my)
add_subdirectory(q4_K-q8_K-RVV-upstream)
add_subdirectory(iq2_xxs-q8_K-RVV-my-br)
add_subdirectory(iq2_xxs-q8_K-RVV-my-ir)
add_subdirectory(iq2_xxs-q8_K-RVV-upstream)